map_type: costmap
#transform_tolerance: 0.2   # default: 0.2
obstacle_range: 2.5         # default: 2.5
raytrace_range: 3.0         # default: 3.0

observation_sources: laser_scanner

laser_scanner:
    sensor_frame: base_scan
    data_type: LaserScan
    topic: /scan
    expected_update_rate: 3.0
    observation_persistence: 0.0
    marking: true
    clearing: true
    min_obstacle_height: 0.0
    max_obstacle_height: 0.3
