recovery_behavior_enabled: true     # default : true
controller_frequency: 10.0          # default : 20.0
controller_patience: 2.0            # default : 15.0, fast params: 5.0
planner_patience: 2.0               # default : 5.0
planner_frequency: 0.2              # default : 0.0
clearing_radius: 0.6                # default : not found
clearing_rotation_allowed: false    # default : true
oscillation_distance: 2.0           # default : 0.5
shutdown_costmaps: false            # default : false
recovery_behaviors:
  - name: 'clear_costmap_recovery'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
base_global_planner: global_planner/GlobalPlanner
GlobalPlanner:
    allow_unknown: true         # (bool, default: true)
    default_tolerance: 0.0      # (double, default: 0.0)
    visualize_potential: false  # (bool, default: false)
    use_dijkstra: false         # false means use A*  (bool, default: true)
    use_quadratic: true         # (bool, default: true)
    use_grid_path: false        # (bool, default: false)
    old_navfn_behavior: false   # (bool, default: false)
    lethal_cost: 253            # default: 253, Lethal Cost (dynamic reconfigure) 
    neutral_cost: 50            # (int, default: 50)
    cost_factor: 3.0            # (double, default: 3.)
    publish_potential: true     # (bool, default: True)
    orientation_mode: 0         # (int, default: 0)
    orientation_window_size: 1  # (int, default: 1)
    outline_map: true           # default: true
